name: AppTek hashes
env:
  api_url: "https://api.bitbucket.org/2.0/repositories/omnifluent/apptek_asr/pipelines/"
  auth_token: "-H 'Authorization: Bearer ${{ secrets.APPTEK_BITBUCKET_AUTHENTICATION }}'"
  get_header: "-X GET -s -H 'Accept: application/json'"
  post_header: "-X POST -s -H 'Content-Type: application/json'"
  post_content: '{"target": {"ref_type": "branch", "ref_name": "willi-i6_core-integration", "type": "pipeline_ref_target", "selector": {"type": "custom", "pattern": "hashes-only"}}, "variables": [{"key": "i6_core_branch", "value": "'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-hashes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Start Bitbucket Pipeline
      run: |
        curl ${{ env.post_header }} ${{ env.auth_token}} ${{ env.api_url }} -d '${{ env.post_content }}'${GITHUB_HEAD_REF}'"}]}' |\
        python -c "import sys,json; print(json.load(sys.stdin)['uuid'].replace('{','%7B').replace('}','%7D'))" > pipeline_uuid.txt
    - name: Wait for Results
      run: |
        sleep 300
        while [ COMPLETED != $(\
            curl ${{ env.get_header }} ${{ env.auth_token}} ${{ env.api_url }}$(cat pipeline_uuid.txt) |\
            python3 -c "import sys,json; print(json.load(sys.stdin)['state']['name'])") \
            ]; do sleep 30 ; done
        [ SUCCESSFUL == $(\
            curl ${{ env.get_header }} ${{ env.auth_token}} ${{ env.api_url }}$(cat pipeline_uuid.txt) |\
            python3 -c "import sys,json; print(json.load(sys.stdin)['state']['result']['name'])") \
        ] 
    - name: Report Error
      if: failure()
      run: |
        echo "::error ::The AppTek hashtest pipeline #"$(\
            curl ${{ env.get_header }} ${{ env.auth_token}} ${{ env.api_url }}$(cat pipeline_uuid.txt) |\
            python3 -c "import sys,json; print(json.load(sys.stdin)['build_number'])") \
            " failed. Please contact {wmichel,ebeck}@apptek.com to find out why."

