name: AppTek hashes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-hashes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Start Bitbucket Pipeline
      run: |
        curl -X POST -s -u ${{ secrets.MICHEL_BITBUCKET_AUTHENTICATION }} \
            -H 'Content-Type: application/json' \
            https://api.bitbucket.org/2.0/repositories/omnifluent/apptek_asr/pipelines/ \
            -d '{"target": {"ref_type": "branch", "ref_name": "willi-i6_core-integration",
                 "type": "pipeline_ref_target", "selector": {"type": "custom", "pattern": "hashes-only"}},
                 "variables": [{"key": "i6_core_branch", "value": "'${GITHUB_HEAD_REF}'"}]}' |\
        python -c "import sys,json; print(json.load(sys.stdin)['uuid'])" |\
        sed 's/{/%7B/' | sed 's/}/%7D/' > pipeline_uuid.txt
    - name: Wait for Results
      run: |
        while [ COMPLETED != $(\
            curl -X GET -s -u ${{ secrets.MICHEL_BITBUCKET_AUTHENTICATION }} \
            -H 'Accept: application/json' \
            https://api.bitbucket.org/2.0/repositories/omnifluent/apptek_asr/pipelines/$(cat pipeline_uuid.txt) |\
            python3 -c "import sys,json; print(json.load(sys.stdin)['state']['name'])") \
            ]; do sleep 10 ; done
        [ SUCCESSFUL == $(\
            curl -X GET -s -u ${{ secrets.MICHEL_BITBUCKET_AUTHENTICATION }} \
            -H 'Accept: application/json' \
            https://api.bitbucket.org/2.0/repositories/omnifluent/apptek_asr/pipelines/$(cat pipeline_uuid.txt) |\
            python3 -c "import sys,json; print(json.load(sys.stdin)['state']['result']['name'])") \
        ] 
    - name: Report Error
      if: failure()
      run: |
        echo "::error ::The AppTek hashtest pipeline #"$(\
            curl -X GET -s -u ${{ secrets.MICHEL_BITBUCKET_AUTHENTICATION }} \
            -H 'Accept: application/json' \
            https://api.bitbucket.org/2.0/repositories/omnifluent/apptek_asr/pipelines/$(cat pipeline_uuid.txt) |\
            python3 -c "import sys,json; print(json.load(sys.stdin)['build_number'])") \
            " failed. Please contact {wmichel,ebeck}@apptek.com to find out why."

