name: black
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-black-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
        cache: 'pip'
    - run: pip install click==8.0.4
    - run: pip install black==21.4b2
    - run: black --diff .
    - run: black --check .
